module Packs where

bigBoxes :: [String]
bigBoxes = [
     "Creation and Control"
   , "Honor and Profit"
   , "Order and Chaos"
   , "Data and Destiny"
   , "Reign and Reverie"
   , "Terminal Directive"
   ]

dataPacks :: [String]
dataPacks = [
     "Upstalk"
   , "The Spaces Between"
   , "First Contact"
   , "Up and Over"
   , "All That Remains"
   , "The Source"
   , "The Valley"
   , "Breaker Bay"
   , "Chrome City"
   , "The Underway"
   , "Old Hollywood"
   , "The Universe of Tomorrow"
   , "Kala Ghoda"
   , "Business First"
   , "Democracy and Dogma"
   , "Salsette Island"
   , "The Liberated Mind"
   , "Fear the Masses"
   , "23 Seconds"
   , "Blood Money"
   , "Escalation"
   , "Intervention"
   , "Martial Law"
   , "Quorum"
   , "Daedalus Complex"
   , "Station One"
   , "Earth's Scion"
   , "Blood and Water"
   , "Free Mars"
   , "Crimson Dust"
   , "Sovereign Sight"
   , "Down the White Nile"
   , "Council of the Crest"
   , "The Devil and the Dragon"
   , "Whispers in Nalubaale"
   , "Kampala Ascendent"
   ]
